/**
 * GitHub Sync - Auto-commit y push de SQLite a GitHub
 * Se ejecuta periódicamente para mantener GitHub actualizado
 */

import { checkpoint, getStats } from './client.js';
import { execSync } from 'child_process';

/**
 * Verificar si Git está configurado y funcionando
 */
export function isGitAvailable(): boolean {
  try {
    execSync('git --version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Verificar si tenemos GITHUB_TOKEN configurado
 */
export function isGitHubTokenAvailable(): boolean {
  return !!process.env.GITHUB_TOKEN;
}

/**
 * Configurar Git user para commits
 */
function configureGitUser(): void {
  try {
    execSync('git config user.email "bot@enginedb.app"', { stdio: 'ignore' });
    execSync('git config user.name "EngineDB Bot"', { stdio: 'ignore' });
  } catch (error: any) {
    console.warn('⚠️  Warning configurando git user:', error.message);
  }
}

/**
 * Sincronizar base de datos a GitHub
 */
export async function syncDatabaseToGitHub(): Promise<{
  success: boolean;
  message: string;
  stats?: any;
}> {
  console.log('');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📤 SYNC: Sincronizando database a GitHub...');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

  // Verificar prerrequisitos
  if (!isGitAvailable()) {
    const message = 'Git no está disponible';
    console.error(`❌ ${message}`);
    return { success: false, message };
  }

  if (!isGitHubTokenAvailable()) {
    const message = 'GITHUB_TOKEN no configurado';
    console.error(`❌ ${message}`);
    return { success: false, message };
  }

  try {
    // Paso 1: Checkpoint WAL para consolidar cambios
    console.log('📝 Step 1/6: Haciendo checkpoint de WAL...');
    checkpoint();
    console.log('   ✅ Checkpoint completado');

    // Paso 2: Obtener estadísticas
    console.log('📊 Step 2/6: Obteniendo estadísticas...');
    const stats = getStats();
    console.log(`   📦 ${stats.tables} tablas, ${stats.totalRows} registros`);
    console.log(`   💾 Tamaño: ${(stats.sizeBytes / 1024 / 1024).toFixed(2)} MB`);

    // Paso 3: Configurar Git
    console.log('🔧 Step 3/6: Configurando Git...');
    configureGitUser();
    console.log('   ✅ Git configurado');

    // Paso 4: Verificar si hay cambios
    console.log('🔍 Step 4/6: Verificando cambios...');
    const dbPath = 'api/data/enginedb.sqlite';

    // Agregar archivo
    execSync(`git add ${dbPath}`, { stdio: 'ignore' });

    // Verificar si hay cambios staged
    let hasChanges = false;
    try {
      const status = execSync('git status --porcelain', { encoding: 'utf-8' });
      hasChanges = status.includes(dbPath);
    } catch (error: any) {
      console.warn('⚠️  Warning verificando status:', error.message);
      hasChanges = true; // Asumir que hay cambios
    }

    if (!hasChanges) {
      console.log('   ℹ️  No hay cambios en la base de datos');
      return {
        success: true,
        message: 'No hay cambios',
        stats
      };
    }

    console.log('   ✅ Cambios detectados');

    // Paso 5: Commit
    console.log('💾 Step 5/6: Creando commit...');
    const commitMessage = `Auto-sync database - ${new Date().toISOString()}

📊 Stats:
- Tables: ${stats.tables}
- Rows: ${stats.totalRows.toLocaleString()}
- Size: ${(stats.sizeBytes / 1024 / 1024).toFixed(2)} MB

🤖 Generated by EngineDB Bot`;

    try {
      execSync(`git commit -m "${commitMessage.replace(/"/g, '\\"')}"`, {
        stdio: 'pipe',
        encoding: 'utf-8'
      });
      console.log('   ✅ Commit creado');
    } catch (error: any) {
      // Si el error es "nothing to commit", está bien
      if (error.message.includes('nothing to commit')) {
        console.log('   ℹ️  No hay cambios para commit');
        return {
          success: true,
          message: 'No changes to commit',
          stats
        };
      }
      throw error;
    }

    // Paso 6: Push a GitHub
    console.log('🚀 Step 6/6: Pushing a GitHub...');

    // Configurar remote con token
    const token = process.env.GITHUB_TOKEN;
    const repo = process.env.GITHUB_REPO || 'adriangallery/enginedb';
    const remoteUrl = `https://x-access-token:${token}@github.com/${repo}.git`;

    try {
      // Intentar push
      execSync(`git push ${remoteUrl} HEAD:main`, {
        stdio: 'pipe',
        encoding: 'utf-8',
        timeout: 30000 // 30 segundos timeout
      });
      console.log('   ✅ Push exitoso');
    } catch (error: any) {
      // Si hay conflicto, intentar pull + rebase + push
      if (error.message.includes('rejected') || error.message.includes('non-fast-forward')) {
        console.log('   ⚠️  Conflicto detectado, intentando pull...');

        try {
          // Pull con rebase
          execSync(`git pull ${remoteUrl} main --rebase`, {
            stdio: 'pipe',
            encoding: 'utf-8'
          });

          // Retry push
          execSync(`git push ${remoteUrl} HEAD:main`, {
            stdio: 'pipe',
            encoding: 'utf-8'
          });

          console.log('   ✅ Push exitoso después de rebase');
        } catch (retryError: any) {
          console.error('   ❌ Error en retry:', retryError.message);
          throw retryError;
        }
      } else {
        throw error;
      }
    }

    console.log('');
    console.log('📊 Resumen del sync:');
    console.log(`   ✅ Database sincronizada exitosamente`);
    console.log(`   📦 ${stats.totalRows.toLocaleString()} registros`);
    console.log(`   💾 ${(stats.sizeBytes / 1024 / 1024).toFixed(2)} MB`);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    return {
      success: true,
      message: 'Database sincronizada exitosamente',
      stats
    };
  } catch (error: any) {
    console.error('');
    console.error('❌ Error sincronizando a GitHub:');
    console.error('   ', error.message);
    console.error('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.error('');

    return {
      success: false,
      message: `Error: ${error.message}`
    };
  }
}

/**
 * Verificar si el sync a GitHub está habilitado
 */
export function isGitHubSyncEnabled(): boolean {
  return isGitAvailable() && isGitHubTokenAvailable();
}

export default {
  syncDatabaseToGitHub,
  isGitHubSyncEnabled,
  isGitAvailable,
  isGitHubTokenAvailable,
};
